### ISSUE TITLE
update buildToolsVersion 23.0.3 to 25.0.0 and gradle 2.2.3 to 2.3.1

### ISSUE THREAD

**Issue by kylemathias** [open-learning-exchange/take-home#50]
just wanted to point out this change before https://github.com/open-learning-exchange/take-home/pull/48 is aproved. i dont know if there is a reason we are on older versions.

**Comment by timecomplexity** [comment]
When I first downloaded this project I think Android Studio forced me to update my Gradle version, come to think of it. I don't see a reason not to. I don't believe that the buildToolsVersion has to do with the actual Android version because I think we want it to be built on Ice Cream Sandwich (4.0).
